name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-29"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDdhYzRmNTktZTc3My00NTJlLWE2ZTctY2Y2NzNhZGY3NDQ2IiwidGVuYW50X2lkIjoiYTg3ZTIwMTVhZWUxZjAzYTBmNjI2NDVkYmIyNjNhNWExZWIwYWRjNTZmMjQ3YTU2ODdlOTI1NGQ1MTBiM2IyOSIsImludGVybmFsX3NlY3JldCI6IjgyZTE5OGQzLWYzMjktNDYwMS1hYjNjLTQ5MTQ3MjhkYjBhMyJ9.2KtFUi5pRfQ5_VjgFpcDMMeZbIRJz7IQyTV3gXtjhts"
JWTSecret="This a secret"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1